### ISSUE TITLE
mawer111参与编程马拉松，为期365天

### ISSUE THREAD

**Issue by mawer111** [geekan/coding_marathon#11]
本身是做Android的，暂时没有做项目的想法。
先刷leetcode吧，欢迎大家给建议

**Comment by geekan** [comment]
之前我写了一个“斗鱼老司机”安卓app，功能非常简单，就是接收主播上下线的通知
有没有兴趣完善下，一起做一个包括熊猫、斗鱼、战旗等主流直播平台的汇聚app？

**Comment by mawer111** [comment]
@geekan 可以啊
