### ISSUE TITLE
CharlesPeng参与编程马拉松，为期365天

### ISSUE THREAD

**Issue by pcc09** [geekan/coding_marathon#17]
- github地址：https://github.com/CharlesPeng15
- 相关项目1：https://github.com/CharlesPeng15/Link 一个类似twitter或者新浪微博的平台
- 开始时间：2015/12/30

**Comment by geekan** [comment]
挺有趣的，https://github.com/geekan/coding_marathon/issues/23 也做了一个类似微博的站，或许你们可以聊聊

**Comment by pcc09** [comment]
准备做一个练练手，加油
