### ISSUE TITLE
cloudy9101参加编程马拉松，为期365天

### ISSUE THREAD

**Issue by cloudy9101** [geekan/coding_marathon#28]
- github地址：https://github.com/cloudy9101
- 相关项目1：https://github.com/cloudy9101/datetimepicker
  用 React 写一个 MaterialDesign 风格的日期选择器，练手
- 相关项目2：LeetCode 
- 相关项目3：https://github.com/cloudy9101/zhihu_img
  一个下载知乎答案中的图片的脚本
- 开始时间：2016/01/01
- ps: 其实我是写 ruby 的，后续有项目再贴上 orz

**Comment by cloudy9101** [comment]
day1 时间有点晚，做了两道简单的 LeetCode #292 #258，准备从Easy开始做

**Comment by cloudy9101** [comment]
day2 datetimepicker 完成年月选择，LeetCode #104 #283 #237

**Comment by cloudy9101** [comment]
day3 datetimepicker 完成时间选择，LeetCode #283 #226 #100 #242

**Comment by geekan** [comment]
这刷leetcode是个等差数列？

**Comment by cloudy9101** [comment]
day4 LeetCode #217 #171 #169

**Comment by cloudy9101** [comment]
@geekan  我按难度排了个序 ，从简单的开始，就变这样了... --！

**Comment by cloudy9101** [comment]
day5 datetimepicker 完成日期选择，简单css，LeetCode #235 #191

**Comment by cloudy9101** [comment]
day6 datetimepicker 增加css样式，差点今天就什么都没干了....

**Comment by cloudy9101** [comment]
day7 datetimepicker 增加显示隐藏选择年月 时间面板的逻辑，增加一些美化的 css 。

**Comment by cloudy9101** [comment]
day8 datetimepicker icons 改成 google material icons ， LeetCode #13

**Comment by cloudy9101** [comment]
day9 datetimepicker 日期显示时个位数前加零，修改 css 。

**Comment by cloudy9101** [comment]
day10 LeetCode #206

**Comment by cloudy9101** [comment]
day13 LeetCode #326 #70

**Comment by cloudy9101** [comment]
day18 https://github.com/cloudy9101/zhihu_img 写了一个下载知乎答案图片的脚本，知乎我对不起你...

**Comment by cloudy9101** [comment]
day20 看了一会 RubyFu ，还挺有意思的

**Comment by cloudy9101** [comment]
看了一天 ProGit ，Git 底层只是一个键值数据库。
