### ISSUE TITLE
xlaok参与编程马拉松，为期365天

### ISSUE THREAD

**Issue by xiaok** [geekan/coding_marathon#3]
github地址：https://github.com/xiaok

没有相关项目

开始时间：2015/12/29

**Comment by geekan** [comment]
辐射粉丝路过，打算做哪方面的项目？

**Comment by xiaok** [comment]
正好公司的一个产品打算搞大批量第三方插件，得空写一些

**Comment by xiaok** [comment]
完全没坚持几天，close，其他人加油

**Comment by geekan** [comment]
没有项目和主题果然还是比较难坚持下来
