### ISSUE TITLE
撸了个显示各位参加者Current Streak 的页面

### ISSUE THREAD

**Issue by senghoo** [geekan/coding_marathon#31]
撸了个显示各位参加者Current Streak 的页面

页面地址：http://marathon.itrun.io
项目源码：https://github.com/senghoo/marathon

长时间持续做一件事情比较痛苦，但是路上要是有同伴就会轻松很多。

一起加油！！ 😊

**Comment by Dsljlbaby** [comment]
不错啊

**Comment by geekan** [comment]
👏！

**Comment by geekan** [comment]
可以按照字母序来做个排名

**Comment by senghoo** [comment]
@geekan 现在的排名是根据连击长度来的。 最近连击最长的在前面。

**Comment by mshhmzh** [comment]
^_^，好高效率

**Comment by mshhmzh** [comment]
发现早上哪天迟了起床就麻烦了，晚上下班回来带孩子，要压缩时间才能有空撸代码。以后要规律早起才能坚持每天有代码

**Comment by zzuieliyaoli** [comment]
赞

**Comment by geekan** [comment]
@senghoo 看来我永无第一之日。。哈哈

**Comment by cloudy9101** [comment]
666  感觉可以做个长期竞赛了

**Comment by pcc09** [comment]
加油

**Comment by senghoo** [comment]
@geekan 有空继续完善吧。可以考虑加入当日commit 量排行，但是这样是不是有太浓的竞技味了。

**Comment by youkochan** [comment]
oh no 。。。好像push到似有仓库的并不会显示在这个页面上。。。

**Comment by geekan** [comment]
@youkochan 是的，私有不显示在更新里

**Comment by lujun9972** [comment]
请问 Current Streak，Max Streak，Last Day Count这三个值你是怎么算出来的？

**Comment by senghoo** [comment]
@lujun9972 就是获取commit 后简单计算当前连击， 最大连击，还有最后一天的提交数量啊。
代码是开源的 https://github.com/senghoo/marathon
爬取相关逻辑在：marathon/app/services/marathon_service.rb
计算逻辑在：marathon/app/models/member.rb

**Comment by lujun9972** [comment]
没玩过ruby......
我还以为你是直接从页面中抽取的数据呢。

**Comment by senghoo** [comment]
@lujun9972 
简单说就是
https://github.com/users/senghoo/contributions  
这种地址里可以获得svg格式的每个人每天的contributions 然后扔数据库，计算就是查询。。
